name: "Deploy to GitHub Pages"

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: 'npm'
      - name: Restore Nuxt build cache
        uses: actions/cache@v4
        with:
          path: |
            .nuxt
            .output
          # Chave de cache mais específica para build do Nuxt com npm
          key: ${{ runner.os }}-nuxt-build-${{ hashFiles('''**/package-lock.json''') }}-${{ hashFiles('''app.vue''', '''nuxt.config.ts''', '''pages/**/*.vue''', '''components/**/*.vue''', '''layouts/**/*.vue''') }}
          restore-keys: |
            ${{ runner.os }}-nuxt-build-${{ hashFiles('''**/package-lock.json''') }}-
      - name: Install dependencies
        run: npm ci
      - name: Static HTML export with Nuxt
        run: npm run generate
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./.output/public
  # Job de deploy - este nome é importante para o GitHub Pages
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
